# Generated by Django 4.0 on 2022-12-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_item', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=200)),
                ('icon', models.ImageField(upload_to='media/items/images/')),
            ],
        ),
        migrations.CreateModel(
            name='cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_case', models.CharField(max_length=16)),
                ('icon', models.ImageField(upload_to='media/case/images/')),
                ('name', models.CharField(max_length=200)),
                ('items', models.ManyToManyField(to='chat.item')),
            ],
        ),
    ]
