# Generated by Django 4.0 on 2022-12-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='icon',
            field=models.ImageField(upload_to='case/images/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='icon',
            field=models.ImageField(upload_to='items/images/'),
        ),
    ]
