# Generated by Django 4.0 on 2022-12-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_cases_icon_alter_item_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.CharField(max_length=500)),
            ],
        ),
    ]
