# Generated by Django 4.0 on 2022-12-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='invenory',
            field=models.JSONField(default='{}', null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
