# Generated by Django 4.0 on 2022-12-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_users_invenory_users_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='invenory',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
