# Generated by Django 4.0 on 2022-12-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_users_invenory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='invenory',
            field=models.TextField(),
        ),
    ]
