# Generated by Django 4.0 on 2022-12-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_rename_invenory_users_inventory_cases_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cases',
            name='items',
        ),
        migrations.AddField(
            model_name='cases',
            name='items',
            field=models.JSONField(default=dict),
        ),
    ]
