# Generated by Django 4.0 on 2022-12-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_remove_cases_items_cases_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='Time_term',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cases',
            name='amount_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cases',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cases',
            name='old_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cases',
            name='show_old_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cases',
            name='status',
            field=models.IntegerField(choices=[(2, 'Archive'), (1, 'Expectation'), (0, 'Published')], default=1),
        ),
        migrations.AddField(
            model_name='cases',
            name='term',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cases',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
