# Generated by Django 4.0 on 2022-12-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_cases_time_term_cases_amount_items_cases_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='items',
            field=models.JSONField(default='[{}]'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='status',
            field=models.IntegerField(choices=[(1, 'Expectation'), (0, 'Published'), (2, 'Archive')], default=1),
        ),
    ]
