# Generated by Django 4.0 on 2023-01-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_cases_items_alter_cases_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='status',
            field=models.IntegerField(choices=[(0, 'Published'), (2, 'Archive'), (1, 'Expectation')], default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='id_item',
            field=models.CharField(max_length=32),
        ),
    ]
