# Generated by Django 4.0 on 2023-01-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_cases_status_alter_item_id_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hash_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cases',
            name='status',
            field=models.IntegerField(choices=[(1, 'Expectation'), (2, 'Archive'), (0, 'Published')], default=1),
        ),
    ]
