# Generated by Django 4.0 on 2023-01-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_item_hash_name_alter_cases_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='status',
            field=models.IntegerField(choices=[(1, 'Expectation'), (0, 'Published'), (2, 'Archive')], default=1),
        ),
    ]
