# Generated by Django 4.0 on 2023-01-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_alter_cases_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='tradeLink',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cases',
            name='status',
            field=models.IntegerField(choices=[(2, 'Archive'), (0, 'Published'), (1, 'Expectation')], default=1),
        ),
    ]
