# Generated by Django 4.0 on 2023-01-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_users_tradelink_alter_cases_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cases',
            name='Time_term',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='term',
        ),
        migrations.AddField(
            model_name='cases',
            name='history',
            field=models.JSONField(default='[{}]'),
        ),
        migrations.AddField(
            model_name='cases',
            name='loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cases',
            name='money',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cases',
            name='status',
            field=models.IntegerField(choices=[(1, 'Expectation'), (2, 'Archive'), (0, 'Published')], default=1),
        ),
    ]
