# Generated by Django 4.0 on 2023-01-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_alter_cases_history_alter_cases_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='replenishment',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cases',
            name='status',
            field=models.IntegerField(choices=[(1, 'Expectation'), (0, 'Published'), (2, 'Archive')], default=1),
        ),
    ]
