# Generated by Django 4.0 on 2023-01-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_users_replenishment_alter_cases_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='coef_compensation',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cases',
            name='coef_profit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cases',
            name='rules',
            field=models.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='cases',
            name='testing_history',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='cases',
            name='status',
            field=models.IntegerField(choices=[(2, 'Archive'), (0, 'Published'), (1, 'Expectation')], default=1),
        ),
    ]
