# Generated by Django 4.0 on 2023-01-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_cases_coef_compensation_cases_coef_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='applayRules',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cases',
            name='status',
            field=models.IntegerField(choices=[(2, 'Archive'), (1, 'Expectation'), (0, 'Published')], default=1),
        ),
    ]
