# Generated by Django 4.0 on 2023-01-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_cases_applayrules_alter_cases_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cases',
            name='status',
            field=models.IntegerField(choices=[(0, 'Published'), (1, 'Expectation'), (2, 'Archive')], default=1),
        ),
    ]
